version: "3"
services:
  pld_backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    container_name: pld_backend
    networks:
      - pld
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  pld_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: frontend
    container_name: pld_frontend
    networks:
      - pld
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - pld
    volumes:
    #   - mongodb:/data/db
        - ./initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
networks:
  pld:
    driver: bridge
volumes:
  mongodb:
