auth:
  userAlreadyRegistered: "un utilisateur existe déja avec cette adresse email !"
  userNotFound: "Utilisateur non trouvé !"
  wrongPassword: "Mot de passe incorrect !"
dodStatus:
  todo: 'A faire'
  in_progress: 'En cours'
  done: 'Fini'
